In [2]:
import sys 
sys.path.append('/user-home/1014/code')
from eval_functions import *
from pdp import *

%matplotlib inline

import matplotlib.pyplot as plt

from __future__ import division
import numpy as np
np.random.seed(198908)
import pandas as pd

pd.set_option("display.max_columns",999)

import os
os.environ["JOBLIB_TEMP_FOLDER"] = "/tmp"

from sklearn.externals import joblib

import patsy
from patsy import dmatrix, build_design_matrices

from sklearn.linear_model import LogisticRegressionCV

In [3]:
#read in training data for splines def
x_train=pd.read_csv('/user-home/1014/checking_models/response_rebuild/high_bal_response/mar_orig_trainX.csv')

#train on full
x1= dmatrix("cr(x, df=3) - 1", {"x":x_train.new_hhs_24_NORM_CT.fillna(0).values})
x2= dmatrix("cr(x, df=3) - 1", {"x":x_train.income.fillna(0).values})
x3= dmatrix("cr(x, df=3) - 1", {"x":x_train.Pen_ALL.fillna(0).values})
x4= dmatrix("cr(x, df=3) - 1", {"x":x_train.SHARE_CheckBAL.fillna(0).values})
x5= dmatrix("cr(x, df=3) - 1", {"x":x_train.Target_PreMover_20_Model_879.fillna(0).values})
x6= dmatrix("cr(x, df=3) - 1", {"x":x_train.new_hhs_24_NORM_CT_CHK.fillna(0).values})
x7= dmatrix("cr(x, df=3) - 1", {"x":x_train.new_hhs_24.fillna(0).values})
x8= dmatrix("cr(x, df=3) - 1", {"x":x_train.Pen_Check.fillna(0).values})
x9= dmatrix("cr(x, df=3) - 1", {"x":x_train.pred.fillna(0).values})
x10= dmatrix("cr(x, df=3) - 1", {"x":x_train.Home_value.fillna(0).values})
x11= dmatrix("cr(x, df=3) - 1", {"x":x_train.Mortgage_Liability.fillna(0).values})

In [5]:
#load model
LR=joblib.load('/user-home/1014/checking_models/response_rebuild/high_bal_response/mar_orig_lrmod.pkl')

In [13]:
#import data to score 
pred_score = pd.read_csv('/user-home/1014/checking_models/response_rebuild/high_bal_response/score_july18/scored_final_jul18.csv' )
vars = pd.read_csv('/user-home/1014/checking_models/response_rebuild/high_bal_response/score_july18/toScore.txt' )

x_test=pd.merge(vars, pred_score, left_on='unique_id', right_on='id')
del vars
del pred_score

In [14]:
x_test.head()

,new_hhs_24_NORM_CT,Home_value,Mortgage_Liability,income,closest_dist,Pen_ALL,SHARE_CheckBAL,Target_PreMover_20_Model_879,DEP_BAL_53_TO_NIELSEN,new_hhs_24_NORM_CT_CHK,GPR_IND,IXI_MM_PROP,Advantage_Length_of_Residen_823,DMA_1,DMA_2,DMA_3,DMA_4,DMA_5,DMA_6,DMA_7,DMA_8,DMA_9,DMA_10,DMA_11,DMA_12,DMA_13,DMA_14,DMA_15,DMA_16,DMA_17,DMA_18,DMA_19,DMA_20,DMA_21,DMA_22,new_hhs_24,Pen_Check,unique_id,id,pred
0,0.00875,168.0,NaN,6,3.425082,0.062445,0.008439,40,0.015615,0.001875,23.0,0.171504,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28.0,0.036926,2,2.0,0.012654
1,0.00875,162.0,NaN,6,3.577960,0.062445,0.008439,32,0.015615,0.001875,23.0,0.171504,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28.0,0.036926,3,3.0,0.012044
2,0.00875,184.0,NaN,6,3.577960,0.062445,0.008439,38,0.015615,0.001875,23.0,0.171504,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28.0,0.036926,4,4.0,0.012473
3,0.00875,NaN,NaN,4,3.770929,0.062445,0.008439,24,0.015615,0.001875,23.0,0.171504,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28.0,0.036926,5,5.0,0.012813
4,0.00875,NaN,NaN,1,3.770929,0.062445,0.008439,30,0.015615,0.001875,23.0,0.171504,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,28.0,0.036926,6,6.0,0.012854

In [15]:

xx1=build_design_matrices([x1.design_info], {"x":x_test.new_hhs_24_NORM_CT.fillna(0).values })
xx2=build_design_matrices([x2.design_info], {"x":x_test.income.fillna(0).values })
xx3=build_design_matrices([x3.design_info], {"x":x_test.Pen_ALL.fillna(0).values })
xx4=build_design_matrices([x4.design_info], {"x":x_test.SHARE_CheckBAL.fillna(0).values })
xx5=build_design_matrices([x5.design_info], {"x":x_test.Target_PreMover_20_Model_879.fillna(0).values })
xx6=build_design_matrices([x6.design_info], {"x":x_test.new_hhs_24_NORM_CT_CHK.fillna(0).values })
xx7=build_design_matrices([x7.design_info], {"x":x_test.new_hhs_24.fillna(0).values })
xx8=build_design_matrices([x8.design_info], {"x":x_test.Pen_Check.fillna(0).values })
xx9=build_design_matrices([x9.design_info], {"x":x_test.pred.fillna(0).values })
xx10=build_design_matrices([x10.design_info], {"x":x_test.Home_value.fillna(0).values })
xx11=build_design_matrices([x11.design_info], {"x":x_test.Mortgage_Liability.fillna(0).values })
            
DMA_test=x_test[['DMA_1',
    'DMA_2',
    'DMA_3',
    'DMA_4',
    'DMA_5',
    'DMA_6',
    'DMA_7',
    'DMA_8',
    'DMA_9',
    'DMA_10',
    'DMA_11',
    'DMA_12',
    'DMA_13',
    'DMA_14',
    'DMA_15',
    'DMA_16',
    'DMA_17',
    'DMA_18',
    'DMA_19',
    'DMA_20',
    'DMA_21',
    'DMA_22']]   
    

Z2=np.column_stack(
    [
DMA_test.values,
np.array(xx1[0]),
np.array(xx2[0]),
np.array(xx3[0]),
np.array(xx4[0]),
np.array(xx5[0]),
np.array(xx6[0]),
np.array(xx7[0]),
np.array(xx8[0]),
np.array(xx9[0]),
        np.array(xx10[0]),
np.array(xx11[0])
    ])

pred_new=LR.predict_proba(Z2)[:,1]

In [16]:
toexport=pd.DataFrame(pred_new)
toexport['id']=x_test.id
toexport.columns=['new_pred','id']

          0   id
0  0.003587  2.0
1  0.003395  3.0
2  0.003543  4.0
3  0.003436  5.0
4  0.003653  6.0

In [21]:

def quintile_classify(x):
    if x >= 0.003812:
        quintile=1
    elif x < 0.003812 and x >= 0.003403:
        quintile=2
    elif x < 0.003403 and x >= 0.003109:
        quintile=3
    elif x < 0.003109 and x >= 0.002821:
        quintile=4
    elif x < 0.002821:
        quintile=5
    else:
        quintile =99
    return(quintile)



toexport['quintile']=toexport.new_pred.apply(quintile_classify)

In [22]:
print(toexport.shape)
toexport.head()

(34433930, 3)

   new_pred   id  quintile
0  0.003587  2.0         2
1  0.003395  3.0         3
2  0.003543  4.0         2
3  0.003436  5.0         2
4  0.003653  6.0         2

In [27]:
toexport['original_pred']=x_test.pred
toexport[toexport.original_pred >=0.0153569084145478].groupby('quintile').size()

quintile
1    3065902
2    3928380
3    4100577
4    3937399
5    3564618
dtype: int64

In [24]:
toexport.to_csv('/user-home/1014/checking_models/response_rebuild/high_bal_response/score_july18/july_18_scored.csv', index=False)